{% set name = "seamm-widgets" %}
{% set version = "2024.10.10" %}
{% set sha256 = "4d86465ad1366ec0e73c8f10c164d02caab171243a99e3c89da23bbc8d065d2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-widgets/seamm_widgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pillow
    - pmw
    - python >={{ python_min }}
    - requests
    - seamm-util

test:
  imports:
    - seamm_widgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seam/seamm_widgets
  summary: Tk/Tkinter widgets supporting plug-ins in the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_widgets/

extra:
  recipe-maintainers:
    - paulsaxe
