{% set name = "seamm-widgets" %}
{% set version = "2022.7.29" %}
{% set sha256 = "712c6a5c80534d876a04506dd4313e1ec059c16f389a6d65905e453a9a0d3d17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/99/0f/fe2337571fc754134aaa83582a21540c29b4ab33136816d8642209f5cc1a/seamm_widgets-2022.7.29.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - pillow
    - pmw
    - python >=3.8
    - requests
    - seamm-util

test:
  imports:
    - seamm_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_widgets
  summary: Tk/Tkinter widgets supporting plug-ins in the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_widgets/

extra:
  recipe-maintainers:
    - paulsaxe
