{% set name = "seamm-widgets" %}
{% set version = "2022.10.19" %}
{% set sha256 = "ac0e2345ee34848d1647e8435f809177eb2b814d656ce6ec1f6d7362f5231c1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-widgets/seamm_widgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - pillow
    - pmw
    - python >=3.8
    - requests
    - seamm-util

test:
  imports:
    - seamm_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_widgets
  summary: Tk/Tkinter widgets supporting plug-ins in the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_widgets/

extra:
  recipe-maintainers:
    - paulsaxe
