{% set name = "seamm-widgets" %}
{% set version = "2021.7.24" %}
{% set sha256 = "892df909475cbc9d5ccb005db533bb272a8a1dc681859ff7113e074f8928caf7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-widgets/seamm_widgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - pmw
    - python >=3.7
    - seamm-util >=2021.5.5

test:
  imports:
    - seamm_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_widgets
  summary: Tk/Tkinter widgets supporting plug-ins in the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_widgets/

extra:
  recipe-maintainers:
    - paulsaxe
