{% set name = "seamm-widgets" %}
{% set version = "2025.8.27" %}
{% set sha256 = "9112e48efb3cf25f982b01a58e5bfad2d8a8fd5d30e7eb8cd2769bcdd956c9b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-widgets/seamm_widgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - pillow
    - pmw
    - python >=3.8
    - requests
    - seamm-util

test:
  imports:
    - seamm_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_widgets
  summary: Tk/Tkinter widgets supporting plug-ins in the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_widgets/

extra:
  recipe-maintainers:
    - paulsaxe
